### Obtener todas las películas
GET http://localhost:3000/api/coches
Accept: application/json

###

### Insertar una nueva película
POST http://localhost:3000/api/coches
Content-Type: application/json

{
  "titulo": "El laberinto del loco",
  "director": "Guillermo del Toro",
  "anio": 2006
}

###

### Actualizar una película existente (cambia el ID según corresponda)
PUT http://localhost:3000/api/coches/1
Content-Type: application/json

{
  "titulo": "El laberinto del fauno (Edición restaurada)",
  "director": "Guillermo del Toro",
  "anio": 2006
}

###

### Eliminar una película (cambia el ID según corresponda)
DELETE http://localhost:3000/api/movies/1
Accept: application/json
